### ISSUE TITLE
`OSError: [Errno 36] File name too long` when opening zettels

### ISSUE THREAD

**Issue by tpwo** [tpwo/pyzet#45]
During accidental copy-paste, I've got this error. Probably it's a good idea to validate the zettel ID for add/edit etc. Or at least do a `try..except` there.

```
$ pz edit ────────────────────────────────────────────────────────────────────────────────────────────────────────┤20220108134506
Traceback (most recent call last):
  File "/home/trivvz/.local/bin/pyzet", line 8, in <module>
    sys.exit(main())
  File "/home/trivvz/.local/pipx/venvs/pyzet/lib/python3.8/site-packages/pyzet/main.py", line 40, in main
    return _parse_args(args)
  File "/home/trivvz/.local/pipx/venvs/pyzet/lib/python3.8/site-packages/pyzet/main.py", line 233, in _parse_args
    return _parse_args_with_id(id_, args, config)
  File "/home/trivvz/.local/pipx/venvs/pyzet/lib/python3.8/site-packages/pyzet/main.py", line 295, in _parse_args_with_id
    _validate_id(id_, command, config)
  File "/home/trivvz/.local/pipx/venvs/pyzet/lib/python3.8/site-packages/pyzet/main.py", line 401, in _validate_id
    if not zettel_dir.is_dir():
  File "/usr/lib/python3.8/pathlib.py", line 1422, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/usr/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
OSError: [Errno 36] File name too long: '/home/trivvz/zet/zettels/────────────────────────────────────────────────────────────────────────────────────────────────────────┤20220108134506'
```

**Comment by tpwo** [comment]
I noticed that I must have fixed this issue by introducing a custom validator for zettel ID which checks its length. Also, now `pyzet edit <sth long>` will run `git grep` under the hood, and it doesn't seem to have this issue.
